Componente head stand detail
nediireact/nediireactver2 pull request #18
Opened 2021-08-18 20:52 UTC by GMR027

2021-08-19 01:40 UTC, christopherigm requested changes

2021-08-19 01:40 UTC, christopherigm commented on src/modules/parallax-header-image/parallax-header-image.tsx
> +              <div className='Restaurant red'>
O mas bien algo como `Stand__restaurant-indicator`

2021-08-19 01:40 UTC, christopherigm commented on src/modules/stand-detail/stand-content.tsx
> +            <div className="row">
Quitar esto o moverlo dentro de `StandPhones`

2021-08-19 01:40 UTC, christopherigm commented on src/modules/stand-detail/stand-content.tsx
> +            <div className="row">
`row` no se usa, igual se puede quitar y no pasa nada

2021-08-19 01:40 UTC, christopherigm commented on src/modules/stand-detail/stand-detail.scss
> +}
Agregar espacio debajo de esta linea

2021-08-19 01:40 UTC, christopherigm commented on src/modules/stand-detail/stand-detail.tsx
> +        restaurantIcon='local_dining'
Quitar este prop ya que siempre va a ser el mismo. Usar el valor de `local_dining` directamente dentro del componente `StandParallaxHeaderImage`

2021-08-19 01:40 UTC, christopherigm commented on src/modules/stand-detail/stand-parallax-header-image.scss
> +  }
Creo que esto ya no se usa en este nuevo header

2021-08-19 01:40 UTC, christopherigm commented on src/modules/stand-detail/stand-parallax-header-image.scss
> +  .slogan{
Agregar espacio entre slogan y el `{`

2021-08-19 01:40 UTC, christopherigm commented on src/modules/stand-detail/stand-parallax-header-image.scss
> +  }
Quitar si esto no se usa

2021-08-19 01:40 UTC, christopherigm commented on src/modules/stand-detail/stand-parallax-header-image.tsx
> +                    <i className='material-icons center white-text'>{props.restaurantIcon}</i>
Quitar `{props.restaurantIcon}` y usar `local_dining` directamente.

2021-08-19 01:40 UTC, christopherigm commented on src/modules/stand-detail/stand-phones.tsx
> +                href={props.phone}
Aqui deberia de ser:

`href={element.attributes.phone}`

2021-08-19 01:40 UTC, christopherigm commented on src/modules/stand-detail/stand-phones.tsx
> +                target='_lank'
Corregir esto a `_blank`

2021-08-19 01:40 UTC, christopherigm commented on src/modules/stand-detail/stand-phones.tsx
> +                 <div className='grey-text text-darken-4'>{element.attributes.phone}</div>
Corregir identacion del `div`, y cambiarlo a `span` mejor.

2021-08-19 01:49 UTC, christopherigm requested changes

2021-08-19 01:49 UTC, christopherigm commented on src/modules/parallax-header-image/parallax-header-image.scss
> +  top: -30vh;
Cambiar este top negativo

2021-08-19 18:23 UTC, GMR027 commented on src/modules/parallax-header-image/parallax-header-image.tsx
> +              <div className='Restaurant red'>
listo

2021-08-19 18:23 UTC, GMR027 commented on src/modules/stand-detail/stand-content.tsx
> +            <div className="row">
ya quite el row pero el de quitar y ponerlop en standphones a que te refieres?

2021-08-19 18:23 UTC, GMR027 commented on src/modules/stand-detail/stand-content.tsx
> +      <div className='red'>Hola</div>
listo se ha quitado el hola

2021-08-19 18:23 UTC, GMR027 commented on src/modules/stand-detail/stand-detail.scss
> +}
listo

2021-08-19 18:23 UTC, GMR027 commented on src/modules/stand-detail/stand-detail.tsx
> +        restaurantIcon='local_dining'
listo

2021-08-19 18:23 UTC, GMR027 commented on src/modules/stand-detail/stand-parallax-header-image.scss
> +  .slogan{
listo

2021-08-19 18:23 UTC, GMR027 commented on src/modules/stand-detail/stand-parallax-header-image.tsx
> +                    <i className='material-icons center white-text'>{props.restaurantIcon}</i>
listo

2021-08-19 18:23 UTC, GMR027 commented on src/modules/stand-detail/stand-phones.tsx
> +                target='_lank'
listo

2021-08-19 18:23 UTC, GMR027 commented on src/modules/stand-detail/stand-phones.tsx
> +                 <div className='grey-text text-darken-4'>{element.attributes.phone}</div>
listo

2021-08-20 01:18 UTC, christopherigm approved these changes

2021-08-20 01:45 UTC, merged